### ISSUE TITLE
[Linux] Unable to run VTFEdit:R

### ISSUE THREAD

**Issue by Michael-Soyka** [Trico-Everfire/VTF_Edit_Revitalized#3]
#### Description
When I tried to run it, I got an error about missing `libvtflib.so`

#### What has been done
I set LD_LIBRARY_PATH to VTFEdit:R directory and this fixed the first error, but created two qt 6.7 new ones

#### Screenshots
![image](https://github.com/Trico-Everfire/VTF_Edit_Revitalized/assets/45078459/ad34bc77-86ed-437f-8b59-d0cc87708021)

#### Other Info
Distro: Arch Linux
Kernel: 6.8.7-arch1-1

**Comment by Trico-Everfire** [comment]
This should now be fixed. If the issue still occurs, reopen. If it's a different issue, make a new issue.
